### ISSUE TITLE
Wrong height on list of recent connections

### ISSUE THREAD

**Issue by marcomarsala** [natanfelles/adminer-bootstrap-like#13]
List of recent connections, show on the left of login screen, have fixed height:100px, instead of 100%, and is not scrollable, so many lines are hidden. See attached screenshot.

![Cattura](https://user-images.githubusercontent.com/5349718/107162794-f2dca980-69a5-11eb-8cd2-2736a07afa76.JPG)

**Comment by natanfelles** [comment]
Please, loook if https://github.com/natanfelles/adminer-bootstrap-like/commit/ee666eef0b8b135f9dd88b21b6a8495609b0209d fixed this issue.
