### ISSUE TITLE
Editor errors

### ISSUE THREAD

**Issue by covecove1** [natanfelles/adminer-bootstrap-like#3]
Hello,

when using this theme, Editor is not showing comments instead of column names, and dropdown in edit mode is showing IDs instead of first character column from foreign table.

When I delete the bootstrap css everything is normal and there are no problems.

Please help because I really like your theme and would like to use it for Editor :)

Thanks!

**Comment by natanfelles** [comment]
Hello @covecove1 

Do you found a solution for it? I'm not sure if the Editor has the same Adminer CSS.

A PR would be apreciated. :)
