### ISSUE TITLE
Declaration of plugins

### ISSUE THREAD

**Issue by petr-klimes** [natanfelles/adminer-bootstrap-like#4]
Hi,

after download master and run it i get some warning about wrong declaration on plugin.php. There is missing third optional argument of 2 methods (selectQuery, messageQuery)

```
Warning: Declaration of AdminerPlugin::selectQuery($query, $time) should be compatible with Adminer::selectQuery($H, $vh, $Nc = false) in ***\plugin.php on line 380

Warning: Declaration of AdminerPlugin::messageQuery($query, $time) should be compatible with Adminer::messageQuery($H, $Wh, $Nc = false) in ***\plugin.php on line 380
```

**Comment by natanfelles** [comment]
Hi,

means that the plugins was outdated.

Updated now: https://github.com/natanfelles/adminer-bootstrap-like/commit/150fc877dd355e7e62a57686e0ef7a971ad20249
