### ISSUE TITLE
Menu switches to 'close' automatically

### ISSUE THREAD

**Issue by drsdre** [natanfelles/adminer-bootstrap-like#7]
Hi Natan,

First of all thanks for this theme. It works really pleasant.

Unfortunately whilst using the theme, I'm finding that the menu keeps closing on me after some actions (i.e. the menu localstorage setting change from open to close). This happens more or less random. As far as I can tell, there is no visible/invisible interface element that can perform this action. What could this cause?

Thanks,
Andre

**Comment by natanfelles** [comment]
Hello, @drsdre !

A lateral line is created with javascript. When the mouse hover the line, the sidebar auto close/open.

This video show it: https://www.youtube.com/watch?v=fMFCuaJphVk

**Comment by drsdre** [comment]
Thank you for the full blown video explanation. It's still a bit hard to find the exact point on how to open/close it, but at least it's working.

Cheers,
Andre
